---
# Playbook to run a build pipeline using DroneCI
- name: Reproduce the issue
  hosts: localhost
  roles:
    - role: foo
  tasks:
    - name: Import the inner role
      ansible.builtin.include_role:
        name: foo
